#scheme: http
#hostname: localhost
#reverse-proxy-port: 7080
reverse-proxy-uri: http://localhost:7080
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}

security:
  permit-all:
    - /me
    - /actuator/health/**
    - /docs/**

resource-server-port: 4003
audience: client

server:
  port: ${resource-server-port}
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer}

logging:
  level:
    root: INFO
    org.apache.tomcat: INFO
    #    org.apache.tomcat.util.net.NioEndpoint: INFO

